services:
  postgres:
    image: bitnami/postgresql:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rental_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
